# 상수값 모음

FRAME_LOGIN_ID_BOX = "mainframe_FrameSet0_LoginFrame_form_div_login_div_form_edt_id_input"
FRAME_LOGIN_PW_BOX = "mainframe_FrameSet0_LoginFrame_form_div_login_div_form_edt_pw_input"
FRAME_LOGIN_BTN = "mainframe_FrameSet0_LoginFrame_form_div_login_div_form_btn_loginTextBoxElement"
FRAME_MAIN_POPUP = "mainframe_FrameSet0_WorkSteFrame_POPUP_ID229"
FRAME_MAIN_POPUP_CLOSE_BTN = "form_btn_closeTextBoxElement"
# 주문현황 필터 - 상품별
FRAME_ORDER_STATUS_FILTER_ITEM = "mainframe_FrameSet0_WorkSteFrame_form_div_mainWork_ORD003003_div_Contents_div_Work_div_list_tab_list_tabpage08_tabbuttonTextBoxElement"
# 주문현황 조회기간(시작)
FRAME_ORDER_STATUS_DATE_START = "mainframe_FrameSet0_WorkSteFrame_form_div_mainWork_ORD003003_div_Contents_div_Work_div_search_cal_fromDt_cal_dt_calendaredit_input"
# 주문현황 조회기간(끝)
FRAME_ORDER_STATUS_DATE_END = "mainframe_FrameSet0_WorkSteFrame_form_div_mainWork_ORD003003_div_Contents_div_Work_div_search_cal_toDt_cal_dt_calendaredit_input"

# 주문관리 메뉴 버튼
BTN_HOME_ORDER_MANAGEMENT = "mainframe_FrameSet0_WorkSteFrame_form_div_mainMenu_div_menuLeft_div_icon_btn_ordTextBoxElement"
# 주문현황 메뉴 버튼
BTN_HOME_SUB_ORDER_STATUS = "mainframe_FrameSet0_WorkSteFrame_form_div_mainMenu_div_PopMenu_grd_Menu_body_gridrow_9_cell_9_0_controltreeTextBoxElement"
# 주문현황 조회하기 버튼
BTN_ORDER_STATUS_QUERY = "mainframe_FrameSet0_WorkSteFrame_form_div_mainWork_ORD003003_div_WorkTop_div_Btn_btn_apprTextBoxElement"

# 주문현황 - 날짜 조회 첫번째 Row Item
ITEM_RESULT_ROW_FIRST = "mainframe_FrameSet0_WorkSteFrame_form_div_mainWork_ORD003003_div_Contents_div_Work_div_list_grd_ordItemList_body_gridrow_0"

BTN_ORDER_STATUS_EXPORT_CSV = "mainframe_FrameSet0_WorkSteFrame_form_div_mainWork_ORD003003_div_WorkTop_div_Btn_btn_excelTextBoxElement"