name : New Pull Request Created

on:
  pull_request:
    types:
     - opened

jobs:
  build:
    runs-on: ubunu-latest
    steps:
    - name: action-slack
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        author_name: www-be
        fields: repo,message,author,eventName,ref,workflow
        if_mention: failure,cancelled
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      if: always()
