name : New Pull Request Created

on:
  pull_request:
    types: [opened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get PR Reviewers
        id: get_reviewers
        run: |
          reviewers=$(curl -s -L \
            -H "Authorization: Bearer ${{ secrets.PROJECT_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -X GET "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/requested_reviewers")
          reviewer_list=($(echo $reviewers | jq -r '.users[].login'))
          reviewer_list_str=$(IFS=,; echo "${reviewer_list[*]}")
          echo "reviewer_string_list=$reviewer_list_str" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.PROJECT_TOKEN }}
      - name: Get PR URL
        id: pr_url
        run: |
          pr_url="${{ github.event.pull_request.title }}"
          echo "url=$pr_url" >> $GITHUB_OUTPUT
      - name: Convert To Slack Name
        id: slack_name
        run: |
          pr_reviewer_list=${{ steps.get_reviewers.outputs.reviewer_string_list }}
          slack_reviewer_list=()
          for reviewer in "${pr_reviewer_list[@]}"; do
            if [ "$reviewer" == "hosunghan-0821" ]; then
              slack_reviewer_list+=("${{ secrets.SLACK_USER_ID_JONGHYUN }}")
            else
              slack_reviewer_list+=("unregistered name : $reviewer")
            fi
          done

          slack_mention_string=""

          for reviewer in "${slack_reviewer_list[@]}"; do
            slack_mention_string+=" <@$reviewer>"
          done
          
          echo "slack_reviewers=$slack_mention_string" >> $GITHUB_OUTPUT
      - name: action-slack
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          mention: 'here'
          custom_payload: |
            {
              text: "Pull Request Opened!",
              attachments: [{
                author_name: "Author : ${{ github.event.pull_request.user.login }}",
                fallback: 'fallback',
                color: 'good',
                title: 'PR Reviewers',
                text: '${{ steps.slack_name.outputs.slack_reviewers }}',
                fields: [{
                  title: 'PR Title',
                  value: '${{ github.event.pull_request.title }}',
                  short: true
                },
                {
                  title: 'URL',
                  value: "[${{ github.event.pull_request.title }}]($GITHUB_SERVER_URL/$GITHUB_REPOSITORY/pull/${{ github.event.pull_request.number }})",
                  short: true
                },
                {
                  title: 'long title1',
                  value: 'long value1',
                  short: false
                }],
                actions: [{
                }]
              }]
            }
          if_mention: failure,cancelled
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()
