name : New Pull Request Created

on:
  pull_request:
    types: [opened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get PR Reviewers
        id: get_reviewers
        run: |
          reviewers=$(curl -s -H "Authorization: Bearer ${{ secrets.PROJECT_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          -X GET "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/review-requested" | jq -r '.[].login' | jq -s .)
          echo "reviewers=$reviewers" >>$GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.PROJECT_TOKEN }}
      - name: action-slack
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          icon_emoji: ':octocat:'
          custom_payload: |
            {
              text: "Pull Request Opened!",
              attachments: [{
                author_name: "Author : ${{ github.event.pull_request.user.login }}",
                fallback: 'fallback',
                color: 'good',
                title: 'PR Reviewers',
                text: '${{ steps.get_reviewers.outputs.reviewers }}',
                fields: [{
                  title: 'lower case',
                  value: 'LOWER CASE CHECK'.toLowerCase(),
                  short: true
                },
                {
                  title: 'reverse',
                  value: 'gnirts esrever'.split('').reverse().join(''),
                  short: true
                },
                {
                  title: 'long title1',
                  value: 'long value1',
                  short: false
                }],
                actions: [{
                }]
              }]
            }
          if_mention: failure,cancelled
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()
