name : New Pull Request Created

on:
  pull_request:
    types: [opened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get PR Reviewers
        id: get_reviewers
        run: |
          reviewers=$(curl -s -L \
            -H "Authorization: Bearer ${{ secrets.PROJECT_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -X GET "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/requested_reviewers")
          reviewer_list=$(echo $reviewers | jq -r '.users[].login')
          echo "reviewer_string_list=$reviewer_list" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.PROJECT_TOKEN }}
      - name: Get PR URL
        id: pr_url
        run: |
          pr_url="[${{ github.event.pull_request.title }}]($GITHUB_SERVER_URL/$GITHUB_REPOSITORY/pull/${{ github.event.pull_request.number }})"
          echo "url=$pr_url" >> $GITHUB_OUTPUT
      - name: action-slack
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          mention: 'here'
          custom_payload: |
            {
              text: "Pull Request Opened!",
              attachments: [{
                author_name: "Author : ${{ github.event.pull_request.user.login }}",
                fallback: 'fallback',
                color: 'good',
                title: 'PR Reviewers',
                text: "<!here> @${{ steps.get_reviewers.outputs.reviewer_string_list }}",
                fields: [{
                  title: 'PR Title',
                  value: '${{ steps.pr_url.outputs.url }}',
                  short: true
                },
                {
                  title: 'reverse',
                  value: 'gnirts esrever'.split('').reverse().join(''),
                  short: true
                },
                {
                  title: 'long title1',
                  value: 'long value1',
                  short: false
                }],
                actions: [{
                }]
              }]
            }
          if_mention: failure,cancelled
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()
      - name: action-slack-mention
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          mention: 'here'
          if_mention: failure
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()
          
