name : New Pull Request Created

on:
  pull_request:
    types: [opened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set PR Author
        id: pr_author
        run: echo "::set-output name=author::기안자 - ${{ github.event.pull_request.user.login }}"
    
      - name: action-slack
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          author_name: ${{ steps.pr_author.outputs.author }}
          fields: repo,workflow
          custom: 링크 - ${{ github.event.pull_request.html_url }}
          if_mention: failure,cancelled
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()
